services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=summy
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=summy@gmail.com
      - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 81:80
    secrets:
      - db-password

volumes:
  db-data:

secrets:
  db-password:
    file: secrets/db_password.txt

